import { MigrationInterface, QueryRunner } from 'typeorm';

export class Provincias1756948038674 implements MigrationInterface {
  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
             insert into provincia (nombre,regionRegionId) VALUES
('Chachapoyas', '01'),
('Bagua', '01'),
('Bongará', '01'),
('Condorcanqui', '01'),
('Luya', '01'),
('Rodríguez de Mendoza', '01'),
('Utcubamba', '01'),
('Huaraz', '02'),
('Aija', '02'),
('Antonio Raymondi', '02'),
('Asunción', '02'),
('Bolognesi', '02'),
('Carhuaz', '02'),
('Carlos Fermín Fitzcarrald', '02'),
('Casma', '02'),
('Corongo', '02'),
('Huari', '02'),
('Huarmey', '02'),
('Huaylas', '02'),
('Mariscal Luzuriaga', '02'),
('Ocros', '02'),
('Pallasca', '02'),
('Pomabamba', '02'),
('Recuay', '02'),
('Santa', '02'),
('Sihuas', '02'),
('Yungay', '02'),
('Abancay', '03'),
('Andahuaylas', '03'),
('Antabamba', '03'),
('Aymaraes', '03'),
('Cotabambas', '03'),
('Chincheros', '03'),
('Grau', '03'),
('Arequipa', '04'),
('Camaná', '04'),
('Caravelí', '04'),
('Castilla', '04'),
('Caylloma', '04'),
('Condesuyos', '04'),
('Islay', '04'),
('La Uniòn', '04'),
('Huamanga', '05'),
('Cangallo', '05'),
('Huanca Sancos', '05'),
('Huanta', '05'),
('La Mar', '05'),
('Lucanas', '05'),
('Parinacochas', '05'),
('Pàucar del Sara Sara', '05'),
('Sucre', '05'),
('Víctor Fajardo', '05'),
('Vilcas Huamán', '05'),
('Cajamarca', '06'),
('Cajabamba', '06'),
('Celendín', '06'),
('Chota', '06'),
('Contumazá', '06'),
('Cutervo', '06'),
('Hualgayoc', '06'),
('Jaén', '06'),
('San Ignacio', '06'),
('San Marcos', '06'),
('San Miguel', '06'),
('San Pablo', '06'),
('Santa Cruz', '06'),
('Prov. Const. del Callao', '07'),
('Cusco', '08'),
('Acomayo', '08'),
('Anta', '08'),
('Calca', '08'),
('Canas', '08'),
('Canchis', '08'),
('Chumbivilcas', '08'),
('Espinar', '08'),
('La Convención', '08'),
('Paruro', '08'),
('Paucartambo', '08'),
('Quispicanchi', '08'),
('Urubamba', '08'),
('Huancavelica', '09'),
('Acobamba', '09'),
('Angaraes', '09'),
('Castrovirreyna', '09'),
('Churcampa', '09'),
('Huaytará', '09'),
('Tayacaja', '09'),
('Huánuco', '10'),
('Ambo', '10'),
('Dos de Mayo', '10'),
('Huacaybamba', '10'),
('Huamalíes', '10'),
('Leoncio Prado', '10'),
('Marañón', '10'),
('Pachitea', '10'),
('Puerto Inca', '10'),
('Lauricocha', '10'),
('Yarowilca', '10'),
('Ica', '11'),
('Chincha', '11'),
('Nasca', '11'),
('Palpa', '11'),
('Pisco', '11'),
('Huancayo', '12'),
('Concepción', '12'),
('Chanchamayo', '12'),
('Jauja', '12'),
('Junín', '12'),
('Satipo', '12'),
('Tarma', '12'),
('Yauli', '12'),
('Chupaca', '12'),
('Trujillo', '13'),
('Ascope', '13'),
('Bolívar', '13'),
('Chepén', '13'),
('Julcán', '13'),
('Otuzco', '13'),
('Pacasmayo', '13'),
('Pataz', '13'),
('Sánchez Carrión', '13'),
('Santiago de Chuco', '13'),
('Gran Chimú', '13'),
('Virú', '13'),
('Chiclayo', '14'),
('Ferreñafe', '14'),
('Lambayeque', '14'),
('Lima', '15'),
('Barranca', '15'),
('Cajatambo', '15'),
('Canta', '15'),
('Cañete', '15'),
('Huaral', '15'),
('Huarochirí', '15'),
('Huaura', '15'),
('Oyón', '15'),
('Yauyos', '15'),
('Maynas', '16'),
('Alto Amazonas', '16'),
('Loreto', '16'),
('Mariscal Ramón Castilla', '16'),
('Requena', '16'),
('Ucayali', '16'),
('Datem del Marañón', '16'),
('Putumayo', '16'),
('Tambopata', '17'),
('Manu', '17'),
('Tahuamanu', '17'),
('Mariscal Nieto', '18'),
('General Sánchez Cerro', '18'),
('Ilo', '18'),
('Pasco', '19'),
('Daniel Alcides Carrión', '19'),
('Oxapampa', '19'),
('Piura', '20'),
('Ayabaca', '20'),
('Huancabamba', '20'),
('Morropón', '20'),
('Paita', '20'),
('Sullana', '20'),
('Talara', '20'),
('Sechura', '20'),
('Puno', '21'),
('Azángaro', '21'),
('Carabaya', '21'),
('Chucuito', '21'),
('El Collao', '21'),
('Huancané', '21'),
('Lampa', '21'),
('Melgar', '21'),
('Moho', '21'),
('San Antonio de Putina', '21'),
('San Román', '21'),
('Sandia', '21'),
('Yunguyo', '21'),
('Moyobamba', '22'),
('Bellavista', '22'),
('El Dorado', '22'),
('Huallaga', '22'),
('Lamas', '22'),
('Mariscal Cáceres', '22'),
('Picota', '22'),
('Rioja', '22'),
('San Martín', '22'),
('Tocache', '22'),
('Tacna', '23'),
('Candarave', '23'),
('Jorge Basadre', '23'),
('Tarata', '23'),
('Tumbes', '24'),
('Contralmirante Villar', '24'),
('Zarumilla', '24'),
('Coronel Portillo', '25'),
('Atalaya', '25'),
('Padre Abad', '25'),
('Purús', '25');
`);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`DELETE FROM provincias`);
  }
}
